/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package biblioteca.udb.edu.sv.vistas;

import biblioteca.udb.edu.sv.controlador.UsuarioController;
import biblioteca.udb.edu.sv.entidades.Rol;
import biblioteca.udb.edu.sv.entidades.Usuario;
import biblioteca.udb.edu.sv.tools.LogManager;
import biblioteca.udb.edu.sv.tools.Validaciones;
import java.awt.HeadlessException;
import java.time.LocalDateTime;
import java.util.Arrays;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import org.apache.log4j.Logger;

/**
 *
 * @author Fernando Flamenco
 */
public class CambiarPassFrm extends javax.swing.JFrame {

    private static final Logger logger = LogManager.getLogger(CambiarPassFrm.class);
    private final LoginFrm login;
    private final UsuarioController usuarioController = new UsuarioController();
    /**
     * Creates new form CambiarPassFrm
     */
    public CambiarPassFrm(LoginFrm login) {
        this.login = login;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_change_pass_header = new javax.swing.JPanel();
        lbl_title_change_pass_header = new javax.swing.JLabel();
        pnl_cha_pass_volver = new javax.swing.JPanel();
        lbl_btn_volver_cp = new javax.swing.JLabel();
        lbl_correo = new javax.swing.JLabel();
        txt_correo_change = new javax.swing.JTextField();
        lbl_new_pass = new javax.swing.JLabel();
        txt_pass = new javax.swing.JPasswordField();
        lbl_re_pass = new javax.swing.JLabel();
        txt_re_pass = new javax.swing.JPasswordField();
        btn_cambiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnl_change_pass_header.setBackground(new java.awt.Color(14, 20, 56));

        lbl_title_change_pass_header.setFont(new java.awt.Font("Raleway", 1, 24)); // NOI18N
        lbl_title_change_pass_header.setForeground(new java.awt.Color(255, 215, 0));
        lbl_title_change_pass_header.setText("Cambio de contraseña");

        pnl_cha_pass_volver.setBackground(new java.awt.Color(14, 20, 56));
        pnl_cha_pass_volver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_cha_pass_volverMouseClicked(evt);
            }
        });

        lbl_btn_volver_cp.setFont(new java.awt.Font("Raleway", 1, 14)); // NOI18N
        lbl_btn_volver_cp.setForeground(new java.awt.Color(255, 215, 0));
        lbl_btn_volver_cp.setText("< Volver");

        javax.swing.GroupLayout pnl_cha_pass_volverLayout = new javax.swing.GroupLayout(pnl_cha_pass_volver);
        pnl_cha_pass_volver.setLayout(pnl_cha_pass_volverLayout);
        pnl_cha_pass_volverLayout.setHorizontalGroup(
            pnl_cha_pass_volverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_cha_pass_volverLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_btn_volver_cp)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        pnl_cha_pass_volverLayout.setVerticalGroup(
            pnl_cha_pass_volverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_cha_pass_volverLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_btn_volver_cp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnl_change_pass_headerLayout = new javax.swing.GroupLayout(pnl_change_pass_header);
        pnl_change_pass_header.setLayout(pnl_change_pass_headerLayout);
        pnl_change_pass_headerLayout.setHorizontalGroup(
            pnl_change_pass_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_change_pass_headerLayout.createSequentialGroup()
                .addComponent(pnl_cha_pass_volver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82)
                .addComponent(lbl_title_change_pass_header)
                .addContainerGap(136, Short.MAX_VALUE))
        );
        pnl_change_pass_headerLayout.setVerticalGroup(
            pnl_change_pass_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_cha_pass_volver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnl_change_pass_headerLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lbl_title_change_pass_header)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        lbl_correo.setText("Correo:");

        lbl_new_pass.setText("Nueva Contraseña:");

        lbl_re_pass.setText("Repitir contraseña:");

        txt_re_pass.setToolTipText("");

        btn_cambiar.setText("Cambiar");
        btn_cambiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_cambiarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_change_pass_header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_correo, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_new_pass, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_re_pass, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_cambiar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_re_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_correo_change, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnl_change_pass_header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_correo_change, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_correo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_new_pass))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_re_pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_re_pass))
                .addGap(29, 29, 29)
                .addComponent(btn_cambiar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 74, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void pnl_cha_pass_volverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_cha_pass_volverMouseClicked
        login.setVisible(true);
        dispose();
    }//GEN-LAST:event_pnl_cha_pass_volverMouseClicked

    private void btn_cambiarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cambiarMouseClicked
        try {
            if (Validaciones.validarCamposRequeridos(new JTextField[]{txt_correo_change, txt_pass,txt_re_pass}, new JComboBox[]{})) {
                char[] pass1 = txt_pass.getPassword();
                char[] pass2 = txt_re_pass.getPassword();

                boolean iguales = Arrays.equals(pass1, pass2);

                if (!iguales) {
                    JOptionPane.showMessageDialog(null, "Las contraseñas ingresadas no coinciden.");
                    return;
                }
                
                String correo = txt_correo_change.getText();
                String password = new String(txt_pass.getPassword());

                // Enviar al controlador
                String res = usuarioController.restablecerContrasenia(correo, password);
                int tipoMensaje = res.startsWith("Error")
                ? JOptionPane.ERROR_MESSAGE
                : JOptionPane.INFORMATION_MESSAGE;

                JOptionPane.showMessageDialog(
                    null,           
                    res,            
                    "Resultado",
                    tipoMensaje
                  );
                if(!res.startsWith("Error")){
                    login.setVisible(true);
                    dispose();
                }
            }

        } catch (HeadlessException e) {
            logger.error("Error al procesar el usuario: " + e.getMessage());
            JOptionPane.showMessageDialog(null, "Error inesperado: " + e.getMessage());
        }
    }//GEN-LAST:event_btn_cambiarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CambiarPassFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CambiarPassFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CambiarPassFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CambiarPassFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {}
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cambiar;
    private javax.swing.JLabel lbl_btn_volver_cp;
    private javax.swing.JLabel lbl_correo;
    private javax.swing.JLabel lbl_new_pass;
    private javax.swing.JLabel lbl_re_pass;
    private javax.swing.JLabel lbl_title_change_pass_header;
    private javax.swing.JPanel pnl_cha_pass_volver;
    private javax.swing.JPanel pnl_change_pass_header;
    private javax.swing.JTextField txt_correo_change;
    private javax.swing.JPasswordField txt_pass;
    private javax.swing.JPasswordField txt_re_pass;
    // End of variables declaration//GEN-END:variables
}
