/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package biblioteca.udb.edu.sv.vistas;

import biblioteca.udb.edu.sv.controlador.AuditoriaController;
import biblioteca.udb.edu.sv.controlador.ConfiguracionController;
import biblioteca.udb.edu.sv.entidades.Auditoria;
import biblioteca.udb.edu.sv.entidades.Configuracion;
import biblioteca.udb.edu.sv.tools.LogManager;
import java.awt.HeadlessException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import org.apache.log4j.Logger;



/**
 *
 * @author Fernando Flamenco
 */
public class ConfiguracionFrm extends javax.swing.JFrame {
    private static final Logger logger = LogManager.getLogger(ConfiguracionFrm.class);
    
    private final DashboardFrm dashboardFrm;
    private final DefaultTableModel modeloConfiguracion;
    private final DefaultTableModel modeloAuditoria;
    private final ConfiguracionController configController = new ConfiguracionController();
    private final AuditoriaController auditController = new AuditoriaController();


    /**
     * Creates new form ConfiguracionFrm
     * @param dashboardFrm
     */
     public ConfiguracionFrm(DashboardFrm dashboardFrm) {
        super("Formulario Configuración");
        this.dashboardFrm = dashboardFrm;
        initComponents();
       
        txt_id_config.setVisible(false);
        modeloConfiguracion = (DefaultTableModel) tbl_configuracion.getModel();
        cargarDatosConfig(configController.listar());
        modeloAuditoria = (DefaultTableModel) tbl_auditoria.getModel();
        cargarAuditoria(auditController.listar());
    }
     
    /**
     * El orden que se cargan al modeloConfiguracion es como se mostraran, si se desea se puede cambiar el orden acá
     *
     */
    private void cargarDatosConfig (List<Configuracion> config) {
        modeloConfiguracion.setRowCount(0); // Limpiar tabla
        config.forEach(c -> {
            modeloConfiguracion.addRow(new Object[]{
                c.getIdConfig(),
                c.getParametro(),
                c.getValor(),
                c.getDescripcion(),
                c.getHabilitado()
            });
        });
    }
    
    private void cargarAuditoria (List<Auditoria> audit) {
        modeloAuditoria.setRowCount(0); // Limpiar tabla
        audit.forEach(a -> {
            modeloAuditoria.addRow(new Object[]{
                a.getIdAuditoria(),
                a.getUsuario().getIdUsuario(),
                a.getUsuario().getNombre(),
                a.getFechaAccion(),
                a.getTipoAccion(),
                a.getDetalleAccion()
            });
        });
    }
    
    private void limpiarConfig(){
        txt_id_config.setText("");
        txt_parametro_config.setText("");
        txt_valor_config.setText("");
        txt_descripcion_config.setText("");
        txt_parametro_config.setEditable(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_header_config = new javax.swing.JPanel();
        lbl_title_configuracion = new javax.swing.JLabel();
        pnl_config_volver = new javax.swing.JPanel();
        lbl_btn_volver = new javax.swing.JLabel();
        tabConfig = new javax.swing.JTabbedPane();
        pnl_menu_config = new javax.swing.JPanel();
        pnl_datos_config = new javax.swing.JPanel();
        txt_parametro_config = new javax.swing.JTextField();
        txt_valor_config = new javax.swing.JTextField();
        txt_descripcion_config = new javax.swing.JTextField();
        txt_id_config = new javax.swing.JTextField();
        lbl_parametro_config = new javax.swing.JLabel();
        lbl_valor_config = new javax.swing.JLabel();
        lbl_descripcion_config = new javax.swing.JLabel();
        pnl_acciones_config = new javax.swing.JPanel();
        btn_agregar_config = new javax.swing.JButton();
        btn_editar_config = new javax.swing.JButton();
        btn_eliminar_config = new javax.swing.JButton();
        btn_limpiar_config = new javax.swing.JButton();
        scp_tbl_config = new javax.swing.JScrollPane();
        tbl_configuracion = new javax.swing.JTable();
        pnl_menu_editorial = new javax.swing.JPanel();
        pnl_menu_tipo_documentos = new javax.swing.JPanel();
        pnl_menu_estado_ejemplar = new javax.swing.JPanel();
        pnl_menu_estado_prestamo = new javax.swing.JPanel();
        pnl_menu_auditoria = new javax.swing.JPanel();
        scp_auditoria = new javax.swing.JScrollPane();
        tbl_auditoria = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnl_header_config.setBackground(new java.awt.Color(14, 20, 56));

        lbl_title_configuracion.setFont(new java.awt.Font("Raleway", 1, 24)); // NOI18N
        lbl_title_configuracion.setForeground(new java.awt.Color(255, 215, 0));
        lbl_title_configuracion.setText("Configuración");

        pnl_config_volver.setBackground(new java.awt.Color(14, 20, 56));
        pnl_config_volver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_config_volverMouseClicked(evt);
            }
        });

        lbl_btn_volver.setFont(new java.awt.Font("Raleway", 1, 14)); // NOI18N
        lbl_btn_volver.setForeground(new java.awt.Color(255, 215, 0));
        lbl_btn_volver.setText("< Volver");

        javax.swing.GroupLayout pnl_config_volverLayout = new javax.swing.GroupLayout(pnl_config_volver);
        pnl_config_volver.setLayout(pnl_config_volverLayout);
        pnl_config_volverLayout.setHorizontalGroup(
            pnl_config_volverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_config_volverLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_btn_volver)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        pnl_config_volverLayout.setVerticalGroup(
            pnl_config_volverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_config_volverLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lbl_btn_volver)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnl_header_configLayout = new javax.swing.GroupLayout(pnl_header_config);
        pnl_header_config.setLayout(pnl_header_configLayout);
        pnl_header_configLayout.setHorizontalGroup(
            pnl_header_configLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_header_configLayout.createSequentialGroup()
                .addComponent(pnl_config_volver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(386, 386, 386)
                .addComponent(lbl_title_configuracion)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl_header_configLayout.setVerticalGroup(
            pnl_header_configLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_header_configLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lbl_title_configuracion)
                .addContainerGap(35, Short.MAX_VALUE))
            .addComponent(pnl_config_volver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnl_datos_config.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos"));

        lbl_parametro_config.setText("Parametro:");

        lbl_valor_config.setText("Valor:");

        lbl_descripcion_config.setText("Descripción:");

        javax.swing.GroupLayout pnl_datos_configLayout = new javax.swing.GroupLayout(pnl_datos_config);
        pnl_datos_config.setLayout(pnl_datos_configLayout);
        pnl_datos_configLayout.setHorizontalGroup(
            pnl_datos_configLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_datos_configLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txt_id_config, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(pnl_datos_configLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(pnl_datos_configLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_parametro_config)
                    .addComponent(lbl_valor_config)
                    .addComponent(lbl_descripcion_config))
                .addGap(18, 18, 18)
                .addGroup(pnl_datos_configLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_valor_config, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_parametro_config, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_descripcion_config, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(326, Short.MAX_VALUE))
        );
        pnl_datos_configLayout.setVerticalGroup(
            pnl_datos_configLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_datos_configLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_id_config, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnl_datos_configLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_parametro_config, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_parametro_config))
                .addGap(18, 18, 18)
                .addGroup(pnl_datos_configLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_valor_config, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_valor_config))
                .addGap(18, 18, 18)
                .addGroup(pnl_datos_configLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_descripcion_config, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_descripcion_config))
                .addContainerGap(97, Short.MAX_VALUE))
        );

        pnl_acciones_config.setBorder(javax.swing.BorderFactory.createTitledBorder("Acciones"));

        btn_agregar_config.setText("Agregar");
        btn_agregar_config.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregar_configActionPerformed(evt);
            }
        });

        btn_editar_config.setText("Editar");
        btn_editar_config.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editar_configActionPerformed(evt);
            }
        });

        btn_eliminar_config.setText("Eliminar");
        btn_eliminar_config.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminar_configActionPerformed(evt);
            }
        });

        btn_limpiar_config.setText("Limpiar");
        btn_limpiar_config.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limpiar_configActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_acciones_configLayout = new javax.swing.GroupLayout(pnl_acciones_config);
        pnl_acciones_config.setLayout(pnl_acciones_configLayout);
        pnl_acciones_configLayout.setHorizontalGroup(
            pnl_acciones_configLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_acciones_configLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(pnl_acciones_configLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_limpiar_config, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_eliminar_config, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_editar_config, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_agregar_config, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        pnl_acciones_configLayout.setVerticalGroup(
            pnl_acciones_configLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_acciones_configLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(btn_agregar_config, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_editar_config, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_eliminar_config, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_limpiar_config, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        tbl_configuracion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Parametro", "Valor", "Descripción", "Habilitado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                true, true, true, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_configuracion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_configuracionMouseClicked(evt);
            }
        });
        scp_tbl_config.setViewportView(tbl_configuracion);
        if (tbl_configuracion.getColumnModel().getColumnCount() > 0) {
            tbl_configuracion.getColumnModel().getColumn(0).setMaxWidth(50);
            tbl_configuracion.getColumnModel().getColumn(1).setMinWidth(200);
            tbl_configuracion.getColumnModel().getColumn(1).setPreferredWidth(200);
            tbl_configuracion.getColumnModel().getColumn(1).setMaxWidth(200);
            tbl_configuracion.getColumnModel().getColumn(2).setMinWidth(200);
            tbl_configuracion.getColumnModel().getColumn(2).setPreferredWidth(200);
            tbl_configuracion.getColumnModel().getColumn(2).setMaxWidth(200);
            tbl_configuracion.getColumnModel().getColumn(4).setMinWidth(75);
            tbl_configuracion.getColumnModel().getColumn(4).setPreferredWidth(75);
            tbl_configuracion.getColumnModel().getColumn(4).setMaxWidth(75);
        }

        javax.swing.GroupLayout pnl_menu_configLayout = new javax.swing.GroupLayout(pnl_menu_config);
        pnl_menu_config.setLayout(pnl_menu_configLayout);
        pnl_menu_configLayout.setHorizontalGroup(
            pnl_menu_configLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_menu_configLayout.createSequentialGroup()
                .addContainerGap(811, Short.MAX_VALUE)
                .addComponent(pnl_acciones_config, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(pnl_menu_configLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnl_menu_configLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(pnl_menu_configLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(scp_tbl_config)
                        .addGroup(pnl_menu_configLayout.createSequentialGroup()
                            .addComponent(pnl_datos_config, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 290, Short.MAX_VALUE)))
                    .addContainerGap()))
        );
        pnl_menu_configLayout.setVerticalGroup(
            pnl_menu_configLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_menu_configLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnl_acciones_config, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(307, Short.MAX_VALUE))
            .addGroup(pnl_menu_configLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnl_menu_configLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnl_datos_config, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(scp_tbl_config, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        tabConfig.addTab("Configuración", pnl_menu_config);

        javax.swing.GroupLayout pnl_menu_editorialLayout = new javax.swing.GroupLayout(pnl_menu_editorial);
        pnl_menu_editorial.setLayout(pnl_menu_editorialLayout);
        pnl_menu_editorialLayout.setHorizontalGroup(
            pnl_menu_editorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1095, Short.MAX_VALUE)
        );
        pnl_menu_editorialLayout.setVerticalGroup(
            pnl_menu_editorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 576, Short.MAX_VALUE)
        );

        tabConfig.addTab("Editoriales", pnl_menu_editorial);

        javax.swing.GroupLayout pnl_menu_tipo_documentosLayout = new javax.swing.GroupLayout(pnl_menu_tipo_documentos);
        pnl_menu_tipo_documentos.setLayout(pnl_menu_tipo_documentosLayout);
        pnl_menu_tipo_documentosLayout.setHorizontalGroup(
            pnl_menu_tipo_documentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1095, Short.MAX_VALUE)
        );
        pnl_menu_tipo_documentosLayout.setVerticalGroup(
            pnl_menu_tipo_documentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 576, Short.MAX_VALUE)
        );

        tabConfig.addTab("Tipos de documentos", pnl_menu_tipo_documentos);

        javax.swing.GroupLayout pnl_menu_estado_ejemplarLayout = new javax.swing.GroupLayout(pnl_menu_estado_ejemplar);
        pnl_menu_estado_ejemplar.setLayout(pnl_menu_estado_ejemplarLayout);
        pnl_menu_estado_ejemplarLayout.setHorizontalGroup(
            pnl_menu_estado_ejemplarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1095, Short.MAX_VALUE)
        );
        pnl_menu_estado_ejemplarLayout.setVerticalGroup(
            pnl_menu_estado_ejemplarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 576, Short.MAX_VALUE)
        );

        tabConfig.addTab("Estado de ejemplares", pnl_menu_estado_ejemplar);

        javax.swing.GroupLayout pnl_menu_estado_prestamoLayout = new javax.swing.GroupLayout(pnl_menu_estado_prestamo);
        pnl_menu_estado_prestamo.setLayout(pnl_menu_estado_prestamoLayout);
        pnl_menu_estado_prestamoLayout.setHorizontalGroup(
            pnl_menu_estado_prestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1095, Short.MAX_VALUE)
        );
        pnl_menu_estado_prestamoLayout.setVerticalGroup(
            pnl_menu_estado_prestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 576, Short.MAX_VALUE)
        );

        tabConfig.addTab("Estado de prestamo", pnl_menu_estado_prestamo);

        tbl_auditoria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Usuario ID", "Nombre Usuario", "Fecha", "Acción", "Detalle"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        scp_auditoria.setViewportView(tbl_auditoria);
        if (tbl_auditoria.getColumnModel().getColumnCount() > 0) {
            tbl_auditoria.getColumnModel().getColumn(0).setPreferredWidth(25);
            tbl_auditoria.getColumnModel().getColumn(0).setMaxWidth(25);
            tbl_auditoria.getColumnModel().getColumn(1).setPreferredWidth(75);
            tbl_auditoria.getColumnModel().getColumn(1).setMaxWidth(75);
            tbl_auditoria.getColumnModel().getColumn(2).setPreferredWidth(150);
            tbl_auditoria.getColumnModel().getColumn(2).setMaxWidth(150);
            tbl_auditoria.getColumnModel().getColumn(3).setPreferredWidth(150);
            tbl_auditoria.getColumnModel().getColumn(3).setMaxWidth(150);
            tbl_auditoria.getColumnModel().getColumn(4).setPreferredWidth(125);
            tbl_auditoria.getColumnModel().getColumn(4).setMaxWidth(125);
            tbl_auditoria.getColumnModel().getColumn(5).setMinWidth(50);
            tbl_auditoria.getColumnModel().getColumn(5).setPreferredWidth(50);
        }

        javax.swing.GroupLayout pnl_menu_auditoriaLayout = new javax.swing.GroupLayout(pnl_menu_auditoria);
        pnl_menu_auditoria.setLayout(pnl_menu_auditoriaLayout);
        pnl_menu_auditoriaLayout.setHorizontalGroup(
            pnl_menu_auditoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_menu_auditoriaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scp_auditoria, javax.swing.GroupLayout.DEFAULT_SIZE, 1075, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnl_menu_auditoriaLayout.setVerticalGroup(
            pnl_menu_auditoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_menu_auditoriaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scp_auditoria, javax.swing.GroupLayout.DEFAULT_SIZE, 554, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabConfig.addTab("Auditoría", pnl_menu_auditoria);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_header_config, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tabConfig)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnl_header_config, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabConfig))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void pnl_config_volverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_config_volverMouseClicked
        dashboardFrm.setVisible(true);
        dispose();
    }//GEN-LAST:event_pnl_config_volverMouseClicked

    private void btn_agregar_configActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregar_configActionPerformed
       try {
            String parametro = txt_parametro_config.getText();
            String valor = txt_valor_config.getText();
            String descripcion = txt_descripcion_config.getText();

            Configuracion add = new Configuracion();

            add.setParametro(parametro);
            add.setValor(valor);
            add.setDescripcion(descripcion);
            add.setHabilitado(true);

            // Enviar al controlador
            boolean exito = configController.insertar(add);

            if (exito) {
                limpiarConfig();
                cargarDatosConfig(configController.listar());
                cargarAuditoria(auditController.listar());
                JOptionPane.showMessageDialog(null, "Configuración agregada correctamente.");
            } else {
                JOptionPane.showMessageDialog(null, "Error al agregar la configuración.");
            }

        } catch (HeadlessException e) {
            logger.error("Error al procesar la configuración: " + e.getMessage());
            JOptionPane.showMessageDialog(null, "Error inesperado: " + e.getMessage());
        }
    }//GEN-LAST:event_btn_agregar_configActionPerformed

    private void btn_editar_configActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editar_configActionPerformed
        try {
            Integer idConfig = Integer.parseInt(txt_id_config.getText());
            String parametro = txt_parametro_config.getText();
            String valor = txt_valor_config.getText();
            String descripcion = txt_descripcion_config.getText();

            Configuracion edit = new Configuracion();

            edit.setIdConfig(idConfig);
            edit.setParametro(parametro);
            edit.setValor(valor);
            edit.setDescripcion(descripcion);
            edit.setHabilitado(true);

            // Enviar al controlador
            boolean exito = configController.actualizar(edit);

            if (exito) {
                limpiarConfig();
                cargarDatosConfig(configController.listar());
                cargarAuditoria(auditController.listar());
                JOptionPane.showMessageDialog(null, "Configuración actualizada correctamente.");
            } else {
                JOptionPane.showMessageDialog(null, "Error al actualizar el configuración.");
            }

        } catch (HeadlessException e) {
            logger.error("Error al procesar la configuración: " + e.getMessage());
            JOptionPane.showMessageDialog(null, "Error inesperado: " + e.getMessage());
        }
    }//GEN-LAST:event_btn_editar_configActionPerformed

    private void btn_eliminar_configActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminar_configActionPerformed
        if(txt_id_config.getText().length() > 0){
            if (JOptionPane.showConfirmDialog(null, "Esta seguro de eliminar la configuración con ID: " +  txt_id_config.getText() , "WARNING",
            JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                boolean exito = configController.eliminar(Integer.parseInt(txt_id_config.getText()));
                if (exito) {
                    limpiarConfig();
                    cargarDatosConfig(configController.listar());
                    cargarAuditoria(auditController.listar());
                    JOptionPane.showMessageDialog(null, "Configuración eliminada correctamente.");
                } else {
                    JOptionPane.showMessageDialog(null, "Error al eliminar configuración.");
                }
            }
        }else {
            JOptionPane.showMessageDialog(null, "Debes seleccionar una configuración antes de eliminarlo.");
        }
    }//GEN-LAST:event_btn_eliminar_configActionPerformed

    private void btn_limpiar_configActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limpiar_configActionPerformed
        limpiarConfig();
    }//GEN-LAST:event_btn_limpiar_configActionPerformed

    private void tbl_configuracionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_configuracionMouseClicked
        limpiarConfig();
        int index = tbl_configuracion.getSelectedRow();
        TableModel modeloConfig = tbl_configuracion.getModel();
        txt_id_config.setText(modeloConfig.getValueAt(index, 0).toString());
        txt_parametro_config.setText(modeloConfig.getValueAt(index, 1).toString());
        txt_valor_config.setText(modeloConfig.getValueAt(index, 2).toString());
        txt_descripcion_config.setText(modeloConfig.getValueAt(index, 3).toString());
        txt_parametro_config.setEditable(false);
    }//GEN-LAST:event_tbl_configuracionMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConfiguracionFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConfiguracionFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConfiguracionFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConfiguracionFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
       
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_agregar_config;
    private javax.swing.JButton btn_editar_config;
    private javax.swing.JButton btn_eliminar_config;
    private javax.swing.JButton btn_limpiar_config;
    private javax.swing.JLabel lbl_btn_volver;
    private javax.swing.JLabel lbl_descripcion_config;
    private javax.swing.JLabel lbl_parametro_config;
    private javax.swing.JLabel lbl_title_configuracion;
    private javax.swing.JLabel lbl_valor_config;
    private javax.swing.JPanel pnl_acciones_config;
    private javax.swing.JPanel pnl_config_volver;
    private javax.swing.JPanel pnl_datos_config;
    private javax.swing.JPanel pnl_header_config;
    private javax.swing.JPanel pnl_menu_auditoria;
    private javax.swing.JPanel pnl_menu_config;
    private javax.swing.JPanel pnl_menu_editorial;
    private javax.swing.JPanel pnl_menu_estado_ejemplar;
    private javax.swing.JPanel pnl_menu_estado_prestamo;
    private javax.swing.JPanel pnl_menu_tipo_documentos;
    private javax.swing.JScrollPane scp_auditoria;
    private javax.swing.JScrollPane scp_tbl_config;
    private javax.swing.JTabbedPane tabConfig;
    private javax.swing.JTable tbl_auditoria;
    private javax.swing.JTable tbl_configuracion;
    private javax.swing.JTextField txt_descripcion_config;
    private javax.swing.JTextField txt_id_config;
    private javax.swing.JTextField txt_parametro_config;
    private javax.swing.JTextField txt_valor_config;
    // End of variables declaration//GEN-END:variables
}
