/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package biblioteca.udb.edu.sv.vistas;

/**
 *
 * @author Fernando Flamenco
 */
public class GestionDevolucionFrm extends javax.swing.JFrame {
    
    private final DashboardFrm dashboardFrm;

    /**
     * Creates new form GestionDevolucionFrm
     */
    public GestionDevolucionFrm(DashboardFrm dashboardFrm) {
        this.dashboardFrm = dashboardFrm;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_header_gn_devo = new javax.swing.JPanel();
        lbl_title_gn_devo = new javax.swing.JLabel();
        pnl_gn_devo_volver = new javax.swing.JPanel();
        lbl_btn_volver_gn_devo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnl_header_gn_devo.setBackground(new java.awt.Color(14, 20, 56));

        lbl_title_gn_devo.setFont(new java.awt.Font("Raleway", 1, 24)); // NOI18N
        lbl_title_gn_devo.setForeground(new java.awt.Color(255, 215, 0));
        lbl_title_gn_devo.setText("Devoluciones");

        pnl_gn_devo_volver.setBackground(new java.awt.Color(14, 20, 56));
        pnl_gn_devo_volver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_gn_devo_volverMouseClicked(evt);
            }
        });

        lbl_btn_volver_gn_devo.setFont(new java.awt.Font("Raleway", 1, 14)); // NOI18N
        lbl_btn_volver_gn_devo.setForeground(new java.awt.Color(255, 215, 0));
        lbl_btn_volver_gn_devo.setText("< Volver");

        javax.swing.GroupLayout pnl_gn_devo_volverLayout = new javax.swing.GroupLayout(pnl_gn_devo_volver);
        pnl_gn_devo_volver.setLayout(pnl_gn_devo_volverLayout);
        pnl_gn_devo_volverLayout.setHorizontalGroup(
            pnl_gn_devo_volverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_gn_devo_volverLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_btn_volver_gn_devo)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        pnl_gn_devo_volverLayout.setVerticalGroup(
            pnl_gn_devo_volverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_gn_devo_volverLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lbl_btn_volver_gn_devo)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnl_header_gn_devoLayout = new javax.swing.GroupLayout(pnl_header_gn_devo);
        pnl_header_gn_devo.setLayout(pnl_header_gn_devoLayout);
        pnl_header_gn_devoLayout.setHorizontalGroup(
            pnl_header_gn_devoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_header_gn_devoLayout.createSequentialGroup()
                .addComponent(pnl_gn_devo_volver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(303, 303, 303)
                .addComponent(lbl_title_gn_devo)
                .addContainerGap(559, Short.MAX_VALUE))
        );
        pnl_header_gn_devoLayout.setVerticalGroup(
            pnl_header_gn_devoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_gn_devo_volver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnl_header_gn_devoLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lbl_title_gn_devo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_header_gn_devo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnl_header_gn_devo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 610, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void pnl_gn_devo_volverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_gn_devo_volverMouseClicked
        dashboardFrm.setVisible(true);
        dispose();
    }//GEN-LAST:event_pnl_gn_devo_volverMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionDevolucionFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionDevolucionFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionDevolucionFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionDevolucionFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {}
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbl_btn_volver_gn_devo;
    private javax.swing.JLabel lbl_title_gn_devo;
    private javax.swing.JPanel pnl_gn_devo_volver;
    private javax.swing.JPanel pnl_header_gn_devo;
    // End of variables declaration//GEN-END:variables
}
