/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package biblioteca.udb.edu.sv.vistas;

import biblioteca.udb.edu.sv.controlador.PrestamoController;
import biblioteca.udb.edu.sv.entidades.Ejemplar;
import biblioteca.udb.edu.sv.entidades.EstadoPrestamo;
import biblioteca.udb.edu.sv.entidades.Prestamo;
import biblioteca.udb.edu.sv.entidades.Rol;
import biblioteca.udb.edu.sv.entidades.Usuario;
import biblioteca.udb.edu.sv.tools.RoleManager;
import biblioteca.udb.edu.sv.tools.SesionUsuario;
import biblioteca.udb.edu.sv.tools.StoreUserPrestamo;
import java.time.LocalDate;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Fernando Flamenco
 */
public class GestionDevolucionFrm extends javax.swing.JFrame {
    
    SesionUsuario sesion = SesionUsuario.getInstancia();
    StoreUserPrestamo infoPrest = StoreUserPrestamo.getInstancia();
    private final DashboardFrm dashboardFrm;
    private final DefaultTableModel modelPrestamos;
    
    private final PrestamoController prestController = new PrestamoController();

    /**
     * Creates new form GestionDevolucionFrm
     */
    public GestionDevolucionFrm(DashboardFrm dashboardFrm) {
        this.dashboardFrm = dashboardFrm;
        initComponents();
        
        modelPrestamos = (DefaultTableModel) tbl_mis_prestamos_devo.getModel();
        Usuario user = new Usuario();
        user.setIdUsuario(sesion.getIdUsuario());
        Rol rol = new Rol();
        rol.setNombreRol(sesion.getRol());
        user.setRol(rol);
        cargarMisPrestamos(prestController.listarPorRol(user));
    }
    
    private void cargarMisPrestamos(List<Prestamo> pres){
        modelPrestamos.setRowCount(0); // Limpiar tabla
        pres.forEach(p -> {
            modelPrestamos.addRow(new Object[]{
                p.getPrestamoId(),
                p.getEjemplar().getDocumento().getTitulo(),
                p.getUsuario().getCorreo(),
                p.getFechaPrestamo(),
                p.getFechaDevolucionPrevista(),
                p.getEstadoPrestamo()
            });
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_header_gn_devo = new javax.swing.JPanel();
        lbl_title_gn_devo = new javax.swing.JLabel();
        pnl_gn_devo_volver = new javax.swing.JPanel();
        lbl_btn_volver_gn_devo = new javax.swing.JLabel();
        scp_tbl_devo = new javax.swing.JScrollPane();
        tbl_mis_prestamos_devo = new javax.swing.JTable();
        pnl_search_pres_to_devo = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnl_header_gn_devo.setBackground(new java.awt.Color(14, 20, 56));

        lbl_title_gn_devo.setFont(new java.awt.Font("Raleway", 1, 24)); // NOI18N
        lbl_title_gn_devo.setForeground(new java.awt.Color(255, 215, 0));
        lbl_title_gn_devo.setText("Devoluciones");

        pnl_gn_devo_volver.setBackground(new java.awt.Color(14, 20, 56));
        pnl_gn_devo_volver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_gn_devo_volverMouseClicked(evt);
            }
        });

        lbl_btn_volver_gn_devo.setFont(new java.awt.Font("Raleway", 1, 14)); // NOI18N
        lbl_btn_volver_gn_devo.setForeground(new java.awt.Color(255, 215, 0));
        lbl_btn_volver_gn_devo.setText("< Volver");

        javax.swing.GroupLayout pnl_gn_devo_volverLayout = new javax.swing.GroupLayout(pnl_gn_devo_volver);
        pnl_gn_devo_volver.setLayout(pnl_gn_devo_volverLayout);
        pnl_gn_devo_volverLayout.setHorizontalGroup(
            pnl_gn_devo_volverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_gn_devo_volverLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_btn_volver_gn_devo)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        pnl_gn_devo_volverLayout.setVerticalGroup(
            pnl_gn_devo_volverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_gn_devo_volverLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lbl_btn_volver_gn_devo)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnl_header_gn_devoLayout = new javax.swing.GroupLayout(pnl_header_gn_devo);
        pnl_header_gn_devo.setLayout(pnl_header_gn_devoLayout);
        pnl_header_gn_devoLayout.setHorizontalGroup(
            pnl_header_gn_devoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_header_gn_devoLayout.createSequentialGroup()
                .addComponent(pnl_gn_devo_volver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(354, 354, 354)
                .addComponent(lbl_title_gn_devo)
                .addContainerGap(508, Short.MAX_VALUE))
        );
        pnl_header_gn_devoLayout.setVerticalGroup(
            pnl_header_gn_devoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_gn_devo_volver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnl_header_gn_devoLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lbl_title_gn_devo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tbl_mis_prestamos_devo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Titulo", "Usuario", "Fecha Prestamo", "Fecha Prev. Devolución", "Estado prestamo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbl_mis_prestamos_devo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_mis_prestamos_devoMouseClicked(evt);
            }
        });
        scp_tbl_devo.setViewportView(tbl_mis_prestamos_devo);
        if (tbl_mis_prestamos_devo.getColumnModel().getColumnCount() > 0) {
            tbl_mis_prestamos_devo.getColumnModel().getColumn(0).setMinWidth(50);
            tbl_mis_prestamos_devo.getColumnModel().getColumn(0).setPreferredWidth(50);
            tbl_mis_prestamos_devo.getColumnModel().getColumn(0).setMaxWidth(50);
            tbl_mis_prestamos_devo.getColumnModel().getColumn(5).setMinWidth(125);
            tbl_mis_prestamos_devo.getColumnModel().getColumn(5).setPreferredWidth(125);
            tbl_mis_prestamos_devo.getColumnModel().getColumn(5).setMaxWidth(125);
        }

        javax.swing.GroupLayout pnl_search_pres_to_devoLayout = new javax.swing.GroupLayout(pnl_search_pres_to_devo);
        pnl_search_pres_to_devo.setLayout(pnl_search_pres_to_devoLayout);
        pnl_search_pres_to_devoLayout.setHorizontalGroup(
            pnl_search_pres_to_devoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnl_search_pres_to_devoLayout.setVerticalGroup(
            pnl_search_pres_to_devoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_header_gn_devo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scp_tbl_devo)
                    .addComponent(pnl_search_pres_to_devo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnl_header_gn_devo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(pnl_search_pres_to_devo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(scp_tbl_devo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void pnl_gn_devo_volverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_gn_devo_volverMouseClicked
        dashboardFrm.setVisible(true);
        dispose();
    }//GEN-LAST:event_pnl_gn_devo_volverMouseClicked

    private void tbl_mis_prestamos_devoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_mis_prestamos_devoMouseClicked
        if(RoleManager.tienePermiso("GESTION_DEVOLUCIONES","AGREGAR")){
            int index = tbl_mis_prestamos_devo.getSelectedRow();
            TableModel modeloSol= tbl_mis_prestamos_devo.getModel();
            int idPrestamo = Integer.parseInt(modeloSol.getValueAt(index, 0).toString());
            String tituloSol = modeloSol.getValueAt(index, 1).toString();

            if (JOptionPane.showConfirmDialog(null, "Confirmación de devolución del ejemplar:  " +  tituloSol , "WARNING",
                    JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                        boolean isMora = prestController.genMoraPrestamo(idPrestamo);
                         int idEstaPrestamo = isMora ? 3 : 2;
                        boolean exito = prestController.registrarDevolucion(idPrestamo,LocalDate.now(), idEstaPrestamo);
                        if (exito) {
                            Usuario user = new Usuario();
                            user.setIdUsuario(sesion.getIdUsuario());
                            Rol rol = new Rol();
                            rol.setNombreRol(sesion.getRol());
                            user.setRol(rol);
                            cargarMisPrestamos(prestController.listarPorRol(user));
                            JOptionPane.showMessageDialog(null, "Devolución del ejemplar completado con éxito.", "Devolución de ejemplar", JOptionPane.INFORMATION_MESSAGE);
                        } else {
                            JOptionPane.showMessageDialog(null, "Error al generar devolicion.");
                        }
                    }
        }
    }//GEN-LAST:event_tbl_mis_prestamos_devoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionDevolucionFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionDevolucionFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionDevolucionFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionDevolucionFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {}
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbl_btn_volver_gn_devo;
    private javax.swing.JLabel lbl_title_gn_devo;
    private javax.swing.JPanel pnl_gn_devo_volver;
    private javax.swing.JPanel pnl_header_gn_devo;
    private javax.swing.JPanel pnl_search_pres_to_devo;
    private javax.swing.JScrollPane scp_tbl_devo;
    private javax.swing.JTable tbl_mis_prestamos_devo;
    // End of variables declaration//GEN-END:variables
}
