/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package biblioteca.udb.edu.sv.vistas;

import biblioteca.udb.edu.sv.controlador.MoraController;
import biblioteca.udb.edu.sv.entidades.Mora;
import biblioteca.udb.edu.sv.entidades.Rol;
import biblioteca.udb.edu.sv.entidades.Usuario;
import biblioteca.udb.edu.sv.tools.RoleManager;
import biblioteca.udb.edu.sv.tools.SesionUsuario;
import java.math.BigDecimal;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Fernando Flamenco
 */
public class GestionMoraFrm extends javax.swing.JFrame {
    
    SesionUsuario sesion = SesionUsuario.getInstancia();
    private final DashboardFrm dashboardFrm;
    private final DefaultTableModel modelMora;
    
    private final MoraController moraController = new MoraController();

    /**
     * Creates new form GestionMora
     */
    public GestionMoraFrm(DashboardFrm dashboardFrm) {
         this.dashboardFrm = dashboardFrm;
        initComponents();
        
        modelMora = (DefaultTableModel) tbl_mis_moras.getModel();
        Usuario user = new Usuario();
        user.setIdUsuario(sesion.getIdUsuario());
        Rol rol = new Rol();
        rol.setNombreRol(sesion.getRol());
        user.setRol(rol);
        cargarMora(moraController.obtenerMoraPendiente(user));
        
    }
    
    private void cargarMora(List<Mora> mor){
        modelMora.setRowCount(0); // Limpiar tabla
        mor.forEach(m -> {
            modelMora.addRow(new Object[]{
                m.getMoraID(),
                m.getPrestamo().getEjemplar().getDocumento().getTitulo(),
                m.getUsuario().getCorreo(),
                m.getPrestamo().getFechaPrestamo(),
                m.getPrestamo().getFechaDevolucionPrevista(),
                m.getDiasRetraso(),
                m.getMonto(),
                m.getPagado(),
                m.getObservaciones()
            });
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_header_gn_mora = new javax.swing.JPanel();
        lbl_title_gn_mora = new javax.swing.JLabel();
        pnl_gn_mora_volver = new javax.swing.JPanel();
        lbl_btn_volver_gn_mora = new javax.swing.JLabel();
        scp_mis_moras = new javax.swing.JScrollPane();
        tbl_mis_moras = new javax.swing.JTable();
        pnl_buscar_moras = new javax.swing.JPanel();
        txt_buscar_mora = new javax.swing.JTextField();
        btn_buscar_mora = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnl_header_gn_mora.setBackground(new java.awt.Color(14, 20, 56));

        lbl_title_gn_mora.setFont(new java.awt.Font("Raleway", 1, 24)); // NOI18N
        lbl_title_gn_mora.setForeground(new java.awt.Color(255, 215, 0));
        lbl_title_gn_mora.setText("Mora");

        pnl_gn_mora_volver.setBackground(new java.awt.Color(14, 20, 56));
        pnl_gn_mora_volver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_gn_mora_volverMouseClicked(evt);
            }
        });

        lbl_btn_volver_gn_mora.setFont(new java.awt.Font("Raleway", 1, 14)); // NOI18N
        lbl_btn_volver_gn_mora.setForeground(new java.awt.Color(255, 215, 0));
        lbl_btn_volver_gn_mora.setText("< Volver");

        javax.swing.GroupLayout pnl_gn_mora_volverLayout = new javax.swing.GroupLayout(pnl_gn_mora_volver);
        pnl_gn_mora_volver.setLayout(pnl_gn_mora_volverLayout);
        pnl_gn_mora_volverLayout.setHorizontalGroup(
            pnl_gn_mora_volverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_gn_mora_volverLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_btn_volver_gn_mora)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        pnl_gn_mora_volverLayout.setVerticalGroup(
            pnl_gn_mora_volverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_gn_mora_volverLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lbl_btn_volver_gn_mora)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnl_header_gn_moraLayout = new javax.swing.GroupLayout(pnl_header_gn_mora);
        pnl_header_gn_mora.setLayout(pnl_header_gn_moraLayout);
        pnl_header_gn_moraLayout.setHorizontalGroup(
            pnl_header_gn_moraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_header_gn_moraLayout.createSequentialGroup()
                .addComponent(pnl_gn_mora_volver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(401, 401, 401)
                .addComponent(lbl_title_gn_mora)
                .addContainerGap(560, Short.MAX_VALUE))
        );
        pnl_header_gn_moraLayout.setVerticalGroup(
            pnl_header_gn_moraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_gn_mora_volver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_header_gn_moraLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_title_gn_mora)
                .addGap(28, 28, 28))
        );

        tbl_mis_moras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Titulo", "Usuario", "Fecha préstamo", "Fecha Devolución", "Días de restraso", "Monto", "Pagado", "Observaciones"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Boolean.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbl_mis_moras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_mis_morasMouseClicked(evt);
            }
        });
        scp_mis_moras.setViewportView(tbl_mis_moras);

        pnl_buscar_moras.setBorder(javax.swing.BorderFactory.createTitledBorder("Buscar Mora"));

        txt_buscar_mora.setToolTipText("Buscar mis moras");

        btn_buscar_mora.setText("Buscar");

        javax.swing.GroupLayout pnl_buscar_morasLayout = new javax.swing.GroupLayout(pnl_buscar_moras);
        pnl_buscar_moras.setLayout(pnl_buscar_morasLayout);
        pnl_buscar_morasLayout.setHorizontalGroup(
            pnl_buscar_morasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_buscar_morasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_buscar_mora, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_buscar_mora)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl_buscar_morasLayout.setVerticalGroup(
            pnl_buscar_morasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_buscar_morasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnl_buscar_morasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_buscar_mora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_buscar_mora))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_header_gn_mora, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scp_mis_moras)
                    .addComponent(pnl_buscar_moras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnl_header_gn_mora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addComponent(pnl_buscar_moras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scp_mis_moras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void pnl_gn_mora_volverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_gn_mora_volverMouseClicked
        dashboardFrm.setVisible(true);
        dispose();
    }//GEN-LAST:event_pnl_gn_mora_volverMouseClicked

    private void tbl_mis_morasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_mis_morasMouseClicked
        if(RoleManager.tienePermiso("GESTION_MORAS","MODIFICAR")){
            int index = tbl_mis_moras.getSelectedRow();
            TableModel modeloConfig = tbl_mis_moras.getModel();
            int idMora = Integer.parseInt(modeloConfig.getValueAt(index, 0).toString());
            BigDecimal monto = new BigDecimal(modeloConfig.getValueAt(index, 6).toString());
            
            Usuario user = new Usuario();
            user.setIdUsuario(sesion.getIdUsuario());
            user.setNombre(sesion.getNombre());
            Rol rol = new Rol();
            rol.setNombreRol(sesion.getRol());
            user.setRol(rol);
            
            if (JOptionPane.showConfirmDialog(null, "Esta seguro de confirmar pago de mora con ID: " +  idMora , "WARNING",
            JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                boolean exito = moraController.pagoMora(idMora,monto,user);
                if (exito) {
                    cargarMora(moraController.obtenerMoraPendiente(user));
                    JOptionPane.showMessageDialog(null, "Pago realizado correctamente.");
                } else {
                    JOptionPane.showMessageDialog(null, "Error al confirmar pago.");
                }
            }
        }else{
            JOptionPane.showMessageDialog(null, "No cuentas con permisos para realizar la acción. Contacta a un adminstrador.");
        }
       
    }//GEN-LAST:event_tbl_mis_morasMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionMoraFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionMoraFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionMoraFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionMoraFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {}
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_buscar_mora;
    private javax.swing.JLabel lbl_btn_volver_gn_mora;
    private javax.swing.JLabel lbl_title_gn_mora;
    private javax.swing.JPanel pnl_buscar_moras;
    private javax.swing.JPanel pnl_gn_mora_volver;
    private javax.swing.JPanel pnl_header_gn_mora;
    private javax.swing.JScrollPane scp_mis_moras;
    private javax.swing.JTable tbl_mis_moras;
    private javax.swing.JTextField txt_buscar_mora;
    // End of variables declaration//GEN-END:variables
}
