/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package biblioteca.udb.edu.sv.vistas;

import biblioteca.udb.edu.sv.controlador.UsuarioController;
import biblioteca.udb.edu.sv.entidades.*;
import biblioteca.udb.edu.sv.tools.LogManager;
import biblioteca.udb.edu.sv.tools.RoleManager;
import java.awt.HeadlessException;
import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import org.apache.log4j.Logger;

/**
 *
 * @author Fernando Flamenco
 */
public class GestionUsuariosFrm extends javax.swing.JFrame {
 private static final Logger logger = LogManager.getLogger(GestionUsuariosFrm.class);
    
    private final DashboardFrm dashboardFrm;
    private final DefaultTableModel modeloUsuarios;
    private final UsuarioController usuarioController = new UsuarioController();

    /**
     * Creates new form GestionUsuariosFrm
     * @param dashboardFrm
     */
    public GestionUsuariosFrm(DashboardFrm dashboardFrm) {
        super("Formulario Gestión de usuario");
        this.dashboardFrm = dashboardFrm;
        initComponents();
        txt_id_usuario.setVisible(false);
        
        modeloUsuarios = (DefaultTableModel) tbl_usuarios.getModel();
        if (RoleManager.tienePermiso("GESTION_USUARIOS", "LISTAR")) {
            cargarDatosUsuarios(usuarioController.listarUsuarios());
        }
        btn_agregar_usuario.setVisible(RoleManager.tienePermiso("GESTION_USUARIOS", "AGREGAR"));
        btn_editar_usuario.setVisible(RoleManager.tienePermiso("GESTION_USUARIOS", "MODIFICAR"));
        btn_eliminar_usuario.setVisible(RoleManager.tienePermiso("GESTION_USUARIOS", "ELIMINAR"));

        cmb_roles_usuario.removeAllItems();
        cmb_roles_usuario.addItem("Seleccione...");
        List<Rol> listaRoles = usuarioController.obtenerRoles();
        listaRoles.forEach(rol -> {
            cmb_roles_usuario.addItem(rol.getNombreRol());
        });

    }
    
   private void cargarDatosUsuarios (List<Usuario> users) {
        modeloUsuarios.setRowCount(0); // Limpiar tabla
        users.forEach(u -> {
            modeloUsuarios.addRow(new Object[]{
                u.getIdUsuario(),
                u.getNombre(),
                u.getCorreo(),
                u.getRol().getNombreRol(),
                u.getFechaRegistro(),
                u.getHabilitado()
            });
        });
    }
   
   private void limpiarUsuario () {
       txt_id_usuario.setText("");
       txt_nombre_usuario.setText("");
       txt_correo_usuario.setText("");
       txt_password_usuario.setText("");
       txt_re_password.setText("");
       cmb_roles_usuario.setSelectedIndex(0);
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_header_usuarios = new javax.swing.JPanel();
        lbl_title_usuarios = new javax.swing.JLabel();
        pnl_usuario_volver = new javax.swing.JPanel();
        lbl_btn_volver_usuario = new javax.swing.JLabel();
        pnl_datos_usuarios = new javax.swing.JPanel();
        txt_nombre_usuario = new javax.swing.JTextField();
        txt_correo_usuario = new javax.swing.JTextField();
        txt_id_usuario = new javax.swing.JTextField();
        lbl_nombre_usuario = new javax.swing.JLabel();
        lbl_correo_usuario = new javax.swing.JLabel();
        lbl_password_usuario = new javax.swing.JLabel();
        lbl_repeat_password = new javax.swing.JLabel();
        lbl_rol_usuario = new javax.swing.JLabel();
        txt_password_usuario = new javax.swing.JPasswordField();
        txt_re_password = new javax.swing.JPasswordField();
        cmb_roles_usuario = new javax.swing.JComboBox<>();
        pnl_acciones_usuarios = new javax.swing.JPanel();
        btn_agregar_usuario = new javax.swing.JButton();
        btn_editar_usuario = new javax.swing.JButton();
        btn_eliminar_usuario = new javax.swing.JButton();
        btn_limpiar_usuario = new javax.swing.JButton();
        scp_tbl_usuarios = new javax.swing.JScrollPane();
        tbl_usuarios = new javax.swing.JTable();
        pnl_filtro_usuario = new javax.swing.JPanel();
        txt_filter_usuario = new javax.swing.JTextField();
        btn_buscar_usuario = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnl_header_usuarios.setBackground(new java.awt.Color(14, 20, 56));

        lbl_title_usuarios.setFont(new java.awt.Font("Raleway", 1, 24)); // NOI18N
        lbl_title_usuarios.setForeground(new java.awt.Color(255, 215, 0));
        lbl_title_usuarios.setText("Gestión Usuarios");

        pnl_usuario_volver.setBackground(new java.awt.Color(14, 20, 56));
        pnl_usuario_volver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_usuario_volverMouseClicked(evt);
            }
        });

        lbl_btn_volver_usuario.setFont(new java.awt.Font("Raleway", 1, 14)); // NOI18N
        lbl_btn_volver_usuario.setForeground(new java.awt.Color(255, 215, 0));
        lbl_btn_volver_usuario.setText("< Volver");

        javax.swing.GroupLayout pnl_usuario_volverLayout = new javax.swing.GroupLayout(pnl_usuario_volver);
        pnl_usuario_volver.setLayout(pnl_usuario_volverLayout);
        pnl_usuario_volverLayout.setHorizontalGroup(
            pnl_usuario_volverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_usuario_volverLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_btn_volver_usuario)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        pnl_usuario_volverLayout.setVerticalGroup(
            pnl_usuario_volverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_usuario_volverLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lbl_btn_volver_usuario)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnl_header_usuariosLayout = new javax.swing.GroupLayout(pnl_header_usuarios);
        pnl_header_usuarios.setLayout(pnl_header_usuariosLayout);
        pnl_header_usuariosLayout.setHorizontalGroup(
            pnl_header_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_header_usuariosLayout.createSequentialGroup()
                .addComponent(pnl_usuario_volver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(340, 340, 340)
                .addComponent(lbl_title_usuarios)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl_header_usuariosLayout.setVerticalGroup(
            pnl_header_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_usuario_volver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnl_header_usuariosLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lbl_title_usuarios)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnl_datos_usuarios.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos"));

        lbl_nombre_usuario.setText("Nombre:");

        lbl_correo_usuario.setText("Correo:");

        lbl_password_usuario.setText("Contraseña:");

        lbl_repeat_password.setText("Repita contraseña:");

        lbl_rol_usuario.setText("Rol:");

        cmb_roles_usuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout pnl_datos_usuariosLayout = new javax.swing.GroupLayout(pnl_datos_usuarios);
        pnl_datos_usuarios.setLayout(pnl_datos_usuariosLayout);
        pnl_datos_usuariosLayout.setHorizontalGroup(
            pnl_datos_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_datos_usuariosLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(pnl_datos_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_rol_usuario)
                    .addComponent(lbl_repeat_password)
                    .addComponent(lbl_nombre_usuario)
                    .addComponent(lbl_correo_usuario)
                    .addComponent(lbl_password_usuario))
                .addGap(18, 18, 18)
                .addGroup(pnl_datos_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_correo_usuario)
                    .addComponent(txt_nombre_usuario)
                    .addComponent(txt_password_usuario)
                    .addComponent(txt_re_password)
                    .addComponent(cmb_roles_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 295, Short.MAX_VALUE)
                .addComponent(txt_id_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnl_datos_usuariosLayout.setVerticalGroup(
            pnl_datos_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_datos_usuariosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_datos_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_datos_usuariosLayout.createSequentialGroup()
                        .addGroup(pnl_datos_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_nombre_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_nombre_usuario))
                        .addGap(18, 18, 18)
                        .addGroup(pnl_datos_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_correo_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_correo_usuario))
                        .addGap(18, 18, 18)
                        .addGroup(pnl_datos_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_password_usuario)
                            .addComponent(txt_password_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnl_datos_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_repeat_password)
                            .addComponent(txt_re_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnl_datos_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_rol_usuario)
                            .addComponent(cmb_roles_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(txt_id_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnl_acciones_usuarios.setBorder(javax.swing.BorderFactory.createTitledBorder("Acciones"));

        btn_agregar_usuario.setText("Agregar");
        btn_agregar_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregar_usuarioActionPerformed(evt);
            }
        });

        btn_editar_usuario.setText("Editar");
        btn_editar_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editar_usuarioActionPerformed(evt);
            }
        });

        btn_eliminar_usuario.setText("Eliminar");
        btn_eliminar_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminar_usuarioActionPerformed(evt);
            }
        });

        btn_limpiar_usuario.setText("Limpiar");
        btn_limpiar_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limpiar_usuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_acciones_usuariosLayout = new javax.swing.GroupLayout(pnl_acciones_usuarios);
        pnl_acciones_usuarios.setLayout(pnl_acciones_usuariosLayout);
        pnl_acciones_usuariosLayout.setHorizontalGroup(
            pnl_acciones_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_acciones_usuariosLayout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(pnl_acciones_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_limpiar_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_eliminar_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_editar_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_agregar_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42))
        );
        pnl_acciones_usuariosLayout.setVerticalGroup(
            pnl_acciones_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_acciones_usuariosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_agregar_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_editar_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_eliminar_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_limpiar_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tbl_usuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Correo", "Rol", "Fecha creación", "Habilitado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                true, true, true, true, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_usuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_usuariosMouseClicked(evt);
            }
        });
        scp_tbl_usuarios.setViewportView(tbl_usuarios);
        if (tbl_usuarios.getColumnModel().getColumnCount() > 0) {
            tbl_usuarios.getColumnModel().getColumn(0).setMinWidth(50);
            tbl_usuarios.getColumnModel().getColumn(0).setPreferredWidth(50);
            tbl_usuarios.getColumnModel().getColumn(0).setMaxWidth(50);
            tbl_usuarios.getColumnModel().getColumn(1).setMinWidth(300);
            tbl_usuarios.getColumnModel().getColumn(1).setPreferredWidth(300);
            tbl_usuarios.getColumnModel().getColumn(1).setMaxWidth(300);
            tbl_usuarios.getColumnModel().getColumn(2).setMinWidth(250);
            tbl_usuarios.getColumnModel().getColumn(2).setPreferredWidth(250);
            tbl_usuarios.getColumnModel().getColumn(2).setMaxWidth(250);
            tbl_usuarios.getColumnModel().getColumn(3).setMinWidth(210);
            tbl_usuarios.getColumnModel().getColumn(3).setPreferredWidth(210);
            tbl_usuarios.getColumnModel().getColumn(3).setMaxWidth(210);
            tbl_usuarios.getColumnModel().getColumn(4).setPreferredWidth(180);
            tbl_usuarios.getColumnModel().getColumn(4).setMaxWidth(180);
            tbl_usuarios.getColumnModel().getColumn(5).setMinWidth(100);
            tbl_usuarios.getColumnModel().getColumn(5).setPreferredWidth(100);
            tbl_usuarios.getColumnModel().getColumn(5).setMaxWidth(100);
        }

        pnl_filtro_usuario.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Filtros", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Raleway", 0, 11))); // NOI18N

        btn_buscar_usuario.setFont(new java.awt.Font("Raleway", 0, 11)); // NOI18N
        btn_buscar_usuario.setText("Buscar");
        btn_buscar_usuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_buscar_usuarioMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnl_filtro_usuarioLayout = new javax.swing.GroupLayout(pnl_filtro_usuario);
        pnl_filtro_usuario.setLayout(pnl_filtro_usuarioLayout);
        pnl_filtro_usuarioLayout.setHorizontalGroup(
            pnl_filtro_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_filtro_usuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_filter_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_buscar_usuario)
                .addContainerGap(283, Short.MAX_VALUE))
        );
        pnl_filtro_usuarioLayout.setVerticalGroup(
            pnl_filtro_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_filtro_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(txt_filter_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btn_buscar_usuario))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_header_usuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnl_datos_usuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pnl_acciones_usuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(pnl_filtro_usuario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(scp_tbl_usuarios, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnl_header_usuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnl_datos_usuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnl_acciones_usuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(pnl_filtro_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scp_tbl_usuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void pnl_usuario_volverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_usuario_volverMouseClicked
        dashboardFrm.setVisible(true);
        dispose();
    }//GEN-LAST:event_pnl_usuario_volverMouseClicked

    private void btn_agregar_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregar_usuarioActionPerformed
        try {
            
            char[] pass1 = txt_password_usuario.getPassword();
            char[] pass2 = txt_re_password.getPassword();
            String rolName = cmb_roles_usuario.getSelectedItem().toString();

            boolean iguales = Arrays.equals(pass1, pass2);

            if (!iguales) {
                JOptionPane.showMessageDialog(null, "Las contraseñas ingresadas no coinciden.");
                return;
            }
            if("Seleccione...".equals(rolName.trim())){
                JOptionPane.showMessageDialog(null, "Debese seleccionar un rol.");
                return;
            }
            
            String nombre = txt_nombre_usuario.getText();
            String correo = txt_correo_usuario.getText();
            String password = new String(txt_password_usuario.getPassword());

            Rol rolUserSelected = usuarioController.obtenerRolByNombre(rolName);
            Usuario modelAction = new Usuario();
            LocalDateTime ahora = LocalDateTime.now();
           
            modelAction.setNombre(nombre);
            modelAction.setCorreo(correo);
            modelAction.setContrasenia(password);
            modelAction.setRol(rolUserSelected);
            modelAction.setFechaRegistro(ahora);
            modelAction.setHabilitado(true);

            // Enviar al controlador
            boolean exito = usuarioController.agregarUsuario(modelAction);

            if (exito) {
                limpiarUsuario();
                cargarDatosUsuarios(usuarioController.listarUsuarios());
                JOptionPane.showMessageDialog(null, "Usuario agregado correctamente.");
            } else {
                JOptionPane.showMessageDialog(null, "Error al agregar el usuario.");
            }

        } catch (HeadlessException e) {
            logger.error("Error al procesar el usuario: " + e.getMessage());
            JOptionPane.showMessageDialog(null, "Error inesperado: " + e.getMessage());
        }
    }//GEN-LAST:event_btn_agregar_usuarioActionPerformed

    private void btn_editar_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editar_usuarioActionPerformed
        try {
            if(txt_id_usuario.getText().equals("")){
                JOptionPane.showMessageDialog(null, "No es posible actualizar el usuario, no existe el registro.");
                return;
            }
           
            String rolName = cmb_roles_usuario.getSelectedItem().toString();
            if("Seleccione...".equals(rolName.trim())){
                JOptionPane.showMessageDialog(null, "Debese seleccionar un rol.");
                return;
            }
            Integer id = Integer.parseInt(txt_id_usuario.getText());
            String nombre = txt_nombre_usuario.getText();
            String correo = txt_correo_usuario.getText();

            Rol rolUserSelected = usuarioController.obtenerRolByNombre(rolName);
            Usuario modelAction = new Usuario();
            LocalDateTime ahora = LocalDateTime.now();
           
            modelAction.setIdUsuario(id);
            modelAction.setNombre(nombre);
            modelAction.setCorreo(correo);
            modelAction.setRol(rolUserSelected);
            modelAction.setHabilitado(true);

            // Enviar al controlador
            boolean exito = usuarioController.editarUsuario(modelAction);

            if (exito) {
                limpiarUsuario();
                cargarDatosUsuarios(usuarioController.listarUsuarios());
                JOptionPane.showMessageDialog(null, "Usuario modificado correctamente.");
            } else {
                JOptionPane.showMessageDialog(null, "Error al actualizar el usuario.");
            }

        } catch (HeadlessException e) {
            logger.error("Error al procesar el usuario: " + e.getMessage());
            JOptionPane.showMessageDialog(null, "Error inesperado: " + e.getMessage());
        }
    }//GEN-LAST:event_btn_editar_usuarioActionPerformed

    private void btn_eliminar_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminar_usuarioActionPerformed
        if(txt_id_usuario.getText().length() > 0){
            if (JOptionPane.showConfirmDialog(null, "Esta seguro de eliminar el usuario con ID: " +  txt_id_usuario.getText() , "WARNING",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            boolean exito = usuarioController.eliminarUsuario(Integer.parseInt(txt_id_usuario.getText()));
            if (exito) {
                limpiarUsuario();
                cargarDatosUsuarios(usuarioController.listarUsuarios());
                JOptionPane.showMessageDialog(null, "Usuario eliminado correctamente.");
            } else {
                JOptionPane.showMessageDialog(null, "Error al eliminar usuario.");
            }
        }
        }else {
            JOptionPane.showMessageDialog(null, "Debes seleccionar un usuario antes de eliminarlo.");
        }
    }//GEN-LAST:event_btn_eliminar_usuarioActionPerformed

    private void btn_limpiar_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limpiar_usuarioActionPerformed
        limpiarUsuario();
    }//GEN-LAST:event_btn_limpiar_usuarioActionPerformed

    private void tbl_usuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_usuariosMouseClicked
        limpiarUsuario();
        int index = tbl_usuarios.getSelectedRow();
        TableModel modeloUser = tbl_usuarios.getModel();
        txt_id_usuario.setText(modeloUser.getValueAt(index, 0).toString());
        txt_nombre_usuario.setText(modeloUser.getValueAt(index, 1).toString());
        txt_correo_usuario.setText(modeloUser.getValueAt(index, 2).toString());
        cmb_roles_usuario.setSelectedItem(modeloUser.getValueAt(index, 3).toString());
    }//GEN-LAST:event_tbl_usuariosMouseClicked

    private void btn_buscar_usuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_buscar_usuarioMouseClicked
        String filter = txt_filter_usuario.getText();
        cargarDatosUsuarios(usuarioController.buscarUsuarios(filter));
        txt_filter_usuario.setText("");
    }//GEN-LAST:event_btn_buscar_usuarioMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionUsuariosFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionUsuariosFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionUsuariosFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionUsuariosFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_agregar_usuario;
    private javax.swing.JButton btn_buscar_usuario;
    private javax.swing.JButton btn_editar_usuario;
    private javax.swing.JButton btn_eliminar_usuario;
    private javax.swing.JButton btn_limpiar_usuario;
    private javax.swing.JComboBox<String> cmb_roles_usuario;
    private javax.swing.JLabel lbl_btn_volver_usuario;
    private javax.swing.JLabel lbl_correo_usuario;
    private javax.swing.JLabel lbl_nombre_usuario;
    private javax.swing.JLabel lbl_password_usuario;
    private javax.swing.JLabel lbl_repeat_password;
    private javax.swing.JLabel lbl_rol_usuario;
    private javax.swing.JLabel lbl_title_usuarios;
    private javax.swing.JPanel pnl_acciones_usuarios;
    private javax.swing.JPanel pnl_datos_usuarios;
    private javax.swing.JPanel pnl_filtro_usuario;
    private javax.swing.JPanel pnl_header_usuarios;
    private javax.swing.JPanel pnl_usuario_volver;
    private javax.swing.JScrollPane scp_tbl_usuarios;
    private javax.swing.JTable tbl_usuarios;
    private javax.swing.JTextField txt_correo_usuario;
    private javax.swing.JTextField txt_filter_usuario;
    private javax.swing.JTextField txt_id_usuario;
    private javax.swing.JTextField txt_nombre_usuario;
    private javax.swing.JPasswordField txt_password_usuario;
    private javax.swing.JPasswordField txt_re_password;
    // End of variables declaration//GEN-END:variables
}
