package biblioteca.udb.edu.sv.vistas;

import biblioteca.udb.edu.sv.entidades.*;
import biblioteca.udb.edu.sv.controlador.*;
import biblioteca.udb.edu.sv.tools.*;
import biblioteca.udb.edu.sv.vistas.DashboardFrm;
import java.awt.HeadlessException;
import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import org.apache.log4j.Logger;

/**
 *
 * @author Fernando Flamenco
 */
public class GestionDocumentosFrm extends javax.swing.JFrame {

    private static final Logger logger = LogManager.getLogger(GestionUsuariosFrm.class);
    public DashboardFrm dashboardFrm;
    private final DefaultTableModel modeloDocumento;
    private final DocumentoController documentoController = new DocumentoController();

    /**
     * Creates new form GestionDocumentosFrm
     */
    public GestionDocumentosFrm(DashboardFrm dashboardFrm) {
        super("Formulario Gestión de usuario");
        this.dashboardFrm = dashboardFrm;

        initComponents();

        modeloDocumento = (DefaultTableModel) tbl_documentos.getModel();
        cargarDatosDocumentos(documentoController.listarDocumentos());

        btn_agregar_documentos.setVisible(RoleManager.tienePermiso("GESTION_USUARIOS", "AGREGAR"));
        btn_editar_documentos.setVisible(RoleManager.tienePermiso("GESTION_USUARIOS", "MODIFICAR"));
        btn_eliminar_documentos.setVisible(RoleManager.tienePermiso("GESTION_USUARIOS", "ELIMINAR"));

        cmb_editorial.removeAllItems();
        cmb_editorial.addItem("Seleccione...");
        List<String> listaEditoriales = documentoController.obtenerEditoriales();
        listaEditoriales.forEach(i -> {
            cmb_editorial.addItem(i);
        });

        cmb_idioma.removeAllItems();
        cmb_idioma.addItem("Seleccione...");
        List<String> listaIdiomas = documentoController.obtenerIdiomas();
        listaIdiomas.forEach(i -> {
            cmb_idioma.addItem(i);
        });

        cmb_categoria.removeAllItems();
        cmb_categoria.addItem("Seleccione...");
        List<String> listaCategorias = documentoController.obtenerCategorias();
        listaCategorias.forEach(i -> {
            cmb_categoria.addItem(i);
        });

        cmb_formato.removeAllItems();
        cmb_formato.addItem("Seleccione...");
        List<String> listaFormatos = documentoController.obtenerFormatos();
        listaFormatos.forEach(i -> {
            cmb_formato.addItem(i);
        });

        cmb_tipo.removeAllItems();
        cmb_tipo.addItem("Seleccione...");
        List<String> listaTipos = documentoController.obtenerTiposDocumento();
        listaTipos.forEach(i -> {
            cmb_tipo.addItem(i);
        });

        cmb_estado.removeAllItems();
        cmb_estado.addItem("Seleccione...");
        List<String> listaEstados = documentoController.obtenerEstadosDocumento();
        listaEstados.forEach(i -> {
            cmb_estado.addItem(i);
        });
    }

    private void cargarDatosDocumentos(List<Documento> documentos) {
        modeloDocumento.setRowCount(0); // Limpiar tabla
        documentos.forEach(doc -> {
            modeloDocumento.addRow(new Object[]{
                doc.getDocumentoID(),
                doc.getTitulo(),
                doc.getAutor(),
                doc.getTipo(),
                doc.getEditorial(),
                doc.getCategoria(),
                doc.getAñoPublicacion(),
                doc.getPaginas(),
                doc.getIdioma(),
                doc.getFormato(),
                doc.getCodigo(),
                doc.getEstado(),});
        });
    }

    private void limpiarDocumento() {
        txt_titulo_documento.setText("");
        txt_año_documento.setText("");
        txt_autor_documento.setText("");
        txt_paginas_documento.setText("");
        txt_observaciones_documento.setText("");
        txt_autor_documento.setText("");
        cmb_editorial.setSelectedIndex(0);
        cmb_tipo.setSelectedIndex(0);
        cmb_estado.setSelectedIndex(0);
        cmb_categoria.setSelectedIndex(0);
        cmb_idioma.setSelectedIndex(0);
        cmb_formato.setSelectedIndex(0);
    }

    private void filtrarDocumentos() {
        String filter = txt_filter_documentos.getText();
        cargarDatosDocumentos(documentoController.buscarDocumentos(filter));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_header_documentos = new javax.swing.JPanel();
        lbl_title_documentos = new javax.swing.JLabel();
        pnl_documentos_volver = new javax.swing.JPanel();
        lbl_btn_volver_documentos = new javax.swing.JLabel();
        pnl_datos_documentos = new javax.swing.JPanel();
        txt_titulo_documento = new javax.swing.JTextField();
        txt_autor_documento = new javax.swing.JTextField();
        lbl_titulo = new javax.swing.JLabel();
        lbl_autor = new javax.swing.JLabel();
        lbl_editorial = new javax.swing.JLabel();
        cmb_editorial = new javax.swing.JComboBox<>();
        cmb_tipo = new javax.swing.JComboBox<>();
        lbl_tipo = new javax.swing.JLabel();
        lbl_año = new javax.swing.JLabel();
        txt_año_documento = new javax.swing.JTextField();
        lbl_idioma_documento = new javax.swing.JLabel();
        lbl_categoria = new javax.swing.JLabel();
        cmb_idioma = new javax.swing.JComboBox<>();
        cmb_categoria = new javax.swing.JComboBox<>();
        lbl_paginas = new javax.swing.JLabel();
        txt_paginas_documento = new javax.swing.JTextField();
        lbl_formato = new javax.swing.JLabel();
        cmb_formato = new javax.swing.JComboBox<>();
        lbl_estado = new javax.swing.JLabel();
        cmb_estado = new javax.swing.JComboBox<>();
        lbl_observaciones = new javax.swing.JLabel();
        txt_observaciones_documento = new javax.swing.JTextField();
        pnl_acciones_documentos = new javax.swing.JPanel();
        btn_agregar_documentos = new javax.swing.JButton();
        btn_editar_documentos = new javax.swing.JButton();
        btn_eliminar_documentos = new javax.swing.JButton();
        btn_limpiar_documentos = new javax.swing.JButton();
        scp_tbl_documentos = new javax.swing.JScrollPane();
        tbl_documentos = new javax.swing.JTable();
        pnl_filtro_documentos = new javax.swing.JPanel();
        txt_filter_documentos = new javax.swing.JTextField();
        btn_buscar_documentos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        pnl_header_documentos.setBackground(new java.awt.Color(14, 20, 56));

        lbl_title_documentos.setFont(new java.awt.Font("Raleway", 1, 24)); // NOI18N
        lbl_title_documentos.setForeground(new java.awt.Color(255, 215, 0));
        lbl_title_documentos.setText("Gestión Documentos");

        pnl_documentos_volver.setBackground(new java.awt.Color(14, 20, 56));
        pnl_documentos_volver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_documentos_volverMouseClicked(evt);
            }
        });

        lbl_btn_volver_documentos.setFont(new java.awt.Font("Raleway", 1, 14)); // NOI18N
        lbl_btn_volver_documentos.setForeground(new java.awt.Color(255, 215, 0));
        lbl_btn_volver_documentos.setText("< Volver");

        javax.swing.GroupLayout pnl_documentos_volverLayout = new javax.swing.GroupLayout(pnl_documentos_volver);
        pnl_documentos_volver.setLayout(pnl_documentos_volverLayout);
        pnl_documentos_volverLayout.setHorizontalGroup(
            pnl_documentos_volverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_documentos_volverLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_btn_volver_documentos)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        pnl_documentos_volverLayout.setVerticalGroup(
            pnl_documentos_volverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_documentos_volverLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lbl_btn_volver_documentos)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnl_header_documentosLayout = new javax.swing.GroupLayout(pnl_header_documentos);
        pnl_header_documentos.setLayout(pnl_header_documentosLayout);
        pnl_header_documentosLayout.setHorizontalGroup(
            pnl_header_documentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_header_documentosLayout.createSequentialGroup()
                .addComponent(pnl_documentos_volver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(340, 340, 340)
                .addComponent(lbl_title_documentos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl_header_documentosLayout.setVerticalGroup(
            pnl_header_documentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_documentos_volver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnl_header_documentosLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lbl_title_documentos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnl_datos_documentos.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos"));

        lbl_titulo.setText("Titulo:");

        lbl_autor.setText("Autor");

        lbl_editorial.setText("Editorial:");

        cmb_editorial.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmb_tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lbl_tipo.setText("Tipo:");

        lbl_año.setText("Año:");

        lbl_idioma_documento.setText("Idioma");

        lbl_categoria.setText("Categoria:");

        cmb_idioma.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmb_categoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lbl_paginas.setText("Paginas:");

        lbl_formato.setText("Formato:");

        cmb_formato.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lbl_estado.setText("Estado:");

        cmb_estado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lbl_observaciones.setText("Observaciones:");

        javax.swing.GroupLayout pnl_datos_documentosLayout = new javax.swing.GroupLayout(pnl_datos_documentos);
        pnl_datos_documentos.setLayout(pnl_datos_documentosLayout);
        pnl_datos_documentosLayout.setHorizontalGroup(
            pnl_datos_documentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_datos_documentosLayout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addGroup(pnl_datos_documentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_titulo)
                    .addComponent(lbl_autor)
                    .addComponent(lbl_editorial)
                    .addComponent(lbl_tipo)
                    .addComponent(lbl_formato)
                    .addComponent(lbl_observaciones))
                .addGap(18, 18, 18)
                .addGroup(pnl_datos_documentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_datos_documentosLayout.createSequentialGroup()
                        .addGroup(pnl_datos_documentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmb_tipo, 0, 130, Short.MAX_VALUE)
                            .addComponent(cmb_formato, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmb_editorial, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(43, 43, 43)
                        .addGroup(pnl_datos_documentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_idioma_documento)
                            .addComponent(lbl_categoria)
                            .addComponent(lbl_estado))
                        .addGap(18, 18, 18)
                        .addGroup(pnl_datos_documentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmb_categoria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmb_estado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmb_idioma, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(pnl_datos_documentosLayout.createSequentialGroup()
                        .addGroup(pnl_datos_documentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_autor_documento, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                            .addComponent(txt_titulo_documento))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnl_datos_documentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnl_datos_documentosLayout.createSequentialGroup()
                                .addComponent(lbl_paginas)
                                .addGap(18, 18, 18)
                                .addComponent(txt_paginas_documento))
                            .addGroup(pnl_datos_documentosLayout.createSequentialGroup()
                                .addComponent(lbl_año)
                                .addGap(18, 18, 18)
                                .addComponent(txt_año_documento, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addComponent(txt_observaciones_documento))
                .addGap(162, 162, 162))
        );
        pnl_datos_documentosLayout.setVerticalGroup(
            pnl_datos_documentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_datos_documentosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_datos_documentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_titulo_documento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_titulo)
                    .addComponent(txt_año_documento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_año))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_datos_documentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_autor_documento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_autor)
                    .addComponent(txt_paginas_documento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_paginas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_datos_documentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnl_datos_documentosLayout.createSequentialGroup()
                        .addGroup(pnl_datos_documentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_editorial)
                            .addComponent(cmb_editorial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnl_datos_documentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_tipo)
                            .addComponent(cmb_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnl_datos_documentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_formato)
                            .addComponent(cmb_formato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnl_datos_documentosLayout.createSequentialGroup()
                        .addGroup(pnl_datos_documentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_idioma_documento)
                            .addComponent(cmb_idioma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnl_datos_documentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_categoria)
                            .addComponent(cmb_categoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnl_datos_documentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_estado)
                            .addComponent(cmb_estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_datos_documentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_observaciones_documento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_observaciones))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        pnl_acciones_documentos.setBorder(javax.swing.BorderFactory.createTitledBorder("Acciones"));

        btn_agregar_documentos.setText("Agregar");
        btn_agregar_documentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregar_documentosActionPerformed(evt);
            }
        });

        btn_editar_documentos.setText("Editar");
        btn_editar_documentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editar_documentosActionPerformed(evt);
            }
        });

        btn_eliminar_documentos.setText("Eliminar");
        btn_eliminar_documentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminar_documentosActionPerformed(evt);
            }
        });

        btn_limpiar_documentos.setText("Limpiar");
        btn_limpiar_documentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limpiar_documentosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_acciones_documentosLayout = new javax.swing.GroupLayout(pnl_acciones_documentos);
        pnl_acciones_documentos.setLayout(pnl_acciones_documentosLayout);
        pnl_acciones_documentosLayout.setHorizontalGroup(
            pnl_acciones_documentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_acciones_documentosLayout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(pnl_acciones_documentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_limpiar_documentos, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_eliminar_documentos, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_editar_documentos, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_agregar_documentos, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42))
        );
        pnl_acciones_documentosLayout.setVerticalGroup(
            pnl_acciones_documentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_acciones_documentosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_agregar_documentos, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_editar_documentos, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_eliminar_documentos, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_limpiar_documentos, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        tbl_documentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Titulo", "Autor", "Tipo", "Editorial", "Categoria", "Año", "Paginas", "Idioma", "Formato", "Codigo", "Habilitado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_documentos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_documentosMouseClicked(evt);
            }
        });
        scp_tbl_documentos.setViewportView(tbl_documentos);

        pnl_filtro_documentos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Filtros", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Raleway", 0, 11))); // NOI18N

        txt_filter_documentos.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_filter_documentosFocusLost(evt);
            }
        });
        txt_filter_documentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_filter_documentosActionPerformed(evt);
            }
        });
        txt_filter_documentos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_filter_documentosKeyTyped(evt);
            }
        });

        btn_buscar_documentos.setFont(new java.awt.Font("Raleway", 0, 11)); // NOI18N
        btn_buscar_documentos.setText("Buscar");
        btn_buscar_documentos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_buscar_documentosMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnl_filtro_documentosLayout = new javax.swing.GroupLayout(pnl_filtro_documentos);
        pnl_filtro_documentos.setLayout(pnl_filtro_documentosLayout);
        pnl_filtro_documentosLayout.setHorizontalGroup(
            pnl_filtro_documentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_filtro_documentosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_filter_documentos, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_buscar_documentos)
                .addContainerGap(283, Short.MAX_VALUE))
        );
        pnl_filtro_documentosLayout.setVerticalGroup(
            pnl_filtro_documentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_filtro_documentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(txt_filter_documentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btn_buscar_documentos))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_header_documentos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnl_datos_documentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pnl_acciones_documentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(pnl_filtro_documentos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(scp_tbl_documentos, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnl_header_documentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnl_acciones_documentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnl_datos_documentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnl_filtro_documentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scp_tbl_documentos, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void pnl_documentos_volverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_documentos_volverMouseClicked
        dashboardFrm.setVisible(true);
        dispose();
    }//GEN-LAST:event_pnl_documentos_volverMouseClicked

    private void btn_agregar_documentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregar_documentosActionPerformed
        try {
            String titulo = txt_titulo_documento.getText().trim();
            String autor = txt_autor_documento.getText().trim();
            String año = txt_año_documento.getText().trim();
            String paginas = txt_paginas_documento.getText().trim();
            String observaciones = txt_observaciones_documento.getText().trim();

            String editorial = cmb_editorial.getSelectedItem().toString();
            String tipo = cmb_tipo.getSelectedItem().toString();
            String categoria = cmb_categoria.getSelectedItem().toString();
            String idioma = cmb_idioma.getSelectedItem().toString();
            String formato = cmb_formato.getSelectedItem().toString();
            boolean estado = cmb_estado.getSelectedItem().toString().equalsIgnoreCase("habilitado");

            if (titulo.isEmpty() || autor.isEmpty() || año.isEmpty() || paginas.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Todos los campos obligatorios deben estar llenos.");
                return;
            }

            if ("Seleccione...".equals(editorial)
                    || "Seleccione...".equals(tipo)
                    || "Seleccione...".equals(categoria)
                    || "Seleccione...".equals(idioma)
                    || "Seleccione...".equals(formato)
                    || "Seleccione...".equals(estado)) {

                JOptionPane.showMessageDialog(null, "Debe seleccionar los valores de todos los combos.");
                return;
            }

            Documento d = new Documento();
            d.setTitulo(titulo);
            d.setAutor(autor);
            d.setAñoPublicacion(Integer.parseInt(año));
            d.setPaginas(Integer.parseInt(paginas));
            d.setObservaciones(observaciones);
            d.setEditorial(editorial);
            d.setTipo(tipo);
            d.setCategoria(categoria);
            d.setIdioma(idioma);
            d.setFormato(formato);
            d.setEstado(estado);
            d.setCodigo(documentoController.generarCodigo(d));

            boolean exito = documentoController.agregarDocumento(d);

            if (exito) {
                limpiarDocumento();
                cargarDatosDocumentos(documentoController.listarDocumentos());
                JOptionPane.showMessageDialog(null, "Documento agregado correctamente.");
            } else {
                JOptionPane.showMessageDialog(null, "Error al agregar el documento.");
            }

        } catch (Exception e) {
            logger.error("Error al procesar documento: " + e.getMessage());
            JOptionPane.showMessageDialog(null, "Error inesperado: " + e.getMessage());
        }
    }//GEN-LAST:event_btn_agregar_documentosActionPerformed

    private void btn_editar_documentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editar_documentosActionPerformed
        try {
            int fila = tbl_documentos.getSelectedRow();
            if (fila == -1) {
                JOptionPane.showMessageDialog(null, "Debe seleccionar un documento para editar.");
                return;
            }

            Integer id = Integer.parseInt(tbl_documentos.getValueAt(fila, 0).toString());

            String titulo = txt_titulo_documento.getText().trim();
            String autor = txt_autor_documento.getText().trim();
            String año = txt_año_documento.getText().trim();
            String paginas = txt_paginas_documento.getText().trim();
            String observaciones = txt_observaciones_documento.getText().trim();

            String editorial = cmb_editorial.getSelectedItem().toString();
            String tipo = cmb_tipo.getSelectedItem().toString();
            String categoria = cmb_categoria.getSelectedItem().toString();
            String idioma = cmb_idioma.getSelectedItem().toString();
            String formato = cmb_formato.getSelectedItem().toString();
            boolean estado = cmb_estado.getSelectedItem().toString().equalsIgnoreCase("habilitado");

            if (titulo.isEmpty() || autor.isEmpty() || año.isEmpty() || paginas.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Todos los campos obligatorios deben estar llenos.");
                return;
            }

            if ("Seleccione...".equals(editorial)
                    || "Seleccione...".equals(tipo)
                    || "Seleccione...".equals(categoria)
                    || "Seleccione...".equals(idioma)
                    || "Seleccione...".equals(formato)) {

                JOptionPane.showMessageDialog(null, "Debe seleccionar los valores de todos los combos.");
                return;
            }

            Documento d = new Documento();
            d.setDocumentoID(id);
            d.setTitulo(titulo);
            d.setAutor(autor);
            d.setAñoPublicacion(Integer.parseInt(año));
            d.setPaginas(Integer.parseInt(paginas));
            d.setObservaciones(observaciones);
            d.setEditorial(editorial);
            d.setTipo(tipo);
            d.setCategoria(categoria);
            d.setIdioma(idioma);
            d.setFormato(formato);
            d.setEstado(estado);

            boolean exito = documentoController.actualizarDocumento(d);

            if (exito) {
                limpiarDocumento();
                cargarDatosDocumentos(documentoController.listarDocumentos());
                JOptionPane.showMessageDialog(null, "Documento modificado correctamente.");
            } else {
                JOptionPane.showMessageDialog(null, "Error al actualizar el documento.");
            }

        } catch (HeadlessException e) {
            logger.error("Error al procesar documento: " + e.getMessage());
            JOptionPane.showMessageDialog(null, "Error inesperado: " + e.getMessage());
        }
    }//GEN-LAST:event_btn_editar_documentosActionPerformed

    private void btn_eliminar_documentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminar_documentosActionPerformed
        int fila = tbl_documentos.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(null, "Debes seleccionar un documento antes de eliminarlo.");
            return;
        }

        String idStr = tbl_documentos.getValueAt(fila, 0).toString();
        String nombre = tbl_documentos.getValueAt(fila, 1).toString();
        int id = Integer.parseInt(idStr);

        int confirm = JOptionPane.showConfirmDialog(
                null,
                "¿Está seguro de eliminar el documento con ID: " + idStr + "?",
                "WARNING",
                JOptionPane.YES_NO_OPTION
        );

        if (confirm == JOptionPane.YES_OPTION) {

            boolean exito = documentoController.eliminarDocumento(nombre, id);

            if (exito) {
                limpiarDocumento();
                cargarDatosDocumentos(documentoController.listarDocumentos());
                JOptionPane.showMessageDialog(null, "Documento eliminado correctamente.");
            } else {
                JOptionPane.showMessageDialog(null, "Error al eliminar documento.");
            }
        }
    }//GEN-LAST:event_btn_eliminar_documentosActionPerformed

    private void btn_limpiar_documentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limpiar_documentosActionPerformed
        limpiarDocumento();
    }//GEN-LAST:event_btn_limpiar_documentosActionPerformed

    private void tbl_documentosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_documentosMouseClicked
        limpiarDocumento();
        int index = tbl_documentos.getSelectedRow();
        TableModel modeloDoc = tbl_documentos.getModel();

        String estado = "Habilitado";
        if (modeloDoc.getValueAt(index, 11).toString().equalsIgnoreCase("false"))
            estado = "Deshabilitado";
        
        txt_titulo_documento.setText(modeloDoc.getValueAt(index, 1).toString());
        txt_autor_documento.setText(modeloDoc.getValueAt(index, 2).toString());
        cmb_tipo.setSelectedItem(modeloDoc.getValueAt(index, 3).toString());
        cmb_editorial.setSelectedItem(modeloDoc.getValueAt(index, 4).toString());
        cmb_categoria.setSelectedItem(modeloDoc.getValueAt(index, 5).toString());
        txt_año_documento.setText(modeloDoc.getValueAt(index, 6).toString());
        txt_paginas_documento.setText(modeloDoc.getValueAt(index, 7).toString());
        cmb_idioma.setSelectedItem(modeloDoc.getValueAt(index, 8).toString());
        cmb_formato.setSelectedItem(modeloDoc.getValueAt(index, 9).toString());
        cmb_estado.setSelectedItem(estado);
    }//GEN-LAST:event_tbl_documentosMouseClicked

    private void btn_buscar_documentosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_buscar_documentosMouseClicked
        filtrarDocumentos();
    }//GEN-LAST:event_btn_buscar_documentosMouseClicked

    private void txt_filter_documentosFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_filter_documentosFocusLost
        filtrarDocumentos();
    }//GEN-LAST:event_txt_filter_documentosFocusLost

    private void txt_filter_documentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_filter_documentosActionPerformed
        filtrarDocumentos();
    }//GEN-LAST:event_txt_filter_documentosActionPerformed

    private void txt_filter_documentosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_filter_documentosKeyTyped
        filtrarDocumentos();
    }//GEN-LAST:event_txt_filter_documentosKeyTyped

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        dashboardFrm.setVisible(true);
        dispose();
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionDocumentosFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionDocumentosFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionDocumentosFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionDocumentosFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_agregar_documentos;
    private javax.swing.JButton btn_buscar_documentos;
    private javax.swing.JButton btn_editar_documentos;
    private javax.swing.JButton btn_eliminar_documentos;
    private javax.swing.JButton btn_limpiar_documentos;
    private javax.swing.JComboBox<String> cmb_categoria;
    private javax.swing.JComboBox<String> cmb_editorial;
    private javax.swing.JComboBox<String> cmb_estado;
    private javax.swing.JComboBox<String> cmb_formato;
    private javax.swing.JComboBox<String> cmb_idioma;
    private javax.swing.JComboBox<String> cmb_tipo;
    private javax.swing.JLabel lbl_autor;
    private javax.swing.JLabel lbl_año;
    private javax.swing.JLabel lbl_btn_volver_documentos;
    private javax.swing.JLabel lbl_categoria;
    private javax.swing.JLabel lbl_editorial;
    private javax.swing.JLabel lbl_estado;
    private javax.swing.JLabel lbl_formato;
    private javax.swing.JLabel lbl_idioma_documento;
    private javax.swing.JLabel lbl_observaciones;
    private javax.swing.JLabel lbl_paginas;
    private javax.swing.JLabel lbl_tipo;
    private javax.swing.JLabel lbl_title_documentos;
    private javax.swing.JLabel lbl_titulo;
    private javax.swing.JPanel pnl_acciones_documentos;
    private javax.swing.JPanel pnl_datos_documentos;
    private javax.swing.JPanel pnl_documentos_volver;
    private javax.swing.JPanel pnl_filtro_documentos;
    private javax.swing.JPanel pnl_header_documentos;
    private javax.swing.JScrollPane scp_tbl_documentos;
    private javax.swing.JTable tbl_documentos;
    private javax.swing.JTextField txt_autor_documento;
    private javax.swing.JTextField txt_año_documento;
    private javax.swing.JTextField txt_filter_documentos;
    private javax.swing.JTextField txt_observaciones_documento;
    private javax.swing.JTextField txt_paginas_documento;
    private javax.swing.JTextField txt_titulo_documento;
    // End of variables declaration//GEN-END:variables
}
