/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package biblioteca.udb.edu.sv.vistas;

import biblioteca.udb.edu.sv.Application;
import biblioteca.udb.edu.sv.tools.LogManager;
import biblioteca.udb.edu.sv.tools.SesionUsuario;
import org.apache.log4j.Logger;
import biblioteca.udb.edu.sv.controlador.UsuarioController;
import biblioteca.udb.edu.sv.entidades.Usuario;
import biblioteca.udb.edu.sv.tools.AuditoriaLogger;
import javax.swing.JOptionPane;

/**
 *
 * @author Fernando Flamenco
 */
public class LoginFrm extends javax.swing.JFrame {
    Logger logger = LogManager.getLogger(Application.class); // just for quick debugging
    private final UsuarioController usuarioController = new UsuarioController();
    
    public LoginFrm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_login_usuario = new javax.swing.JTextField();
        btn_ingresar = new javax.swing.JButton();
        lbl_login_title = new javax.swing.JLabel();
        txt_login_pass = new javax.swing.JPasswordField();
        lbl_username_title = new javax.swing.JLabel();
        lbl_pass_title = new javax.swing.JLabel();
        spt_login = new javax.swing.JSeparator();
        lbl_olv_pass = new javax.swing.JLabel();
        lbl_click_aqui = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txt_login_usuario.setFont(new java.awt.Font("Raleway", 1, 14)); // NOI18N
        txt_login_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_login_usuarioActionPerformed(evt);
            }
        });

        btn_ingresar.setText("Ingresar");
        btn_ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ingresarActionPerformed(evt);
            }
        });

        lbl_login_title.setFont(new java.awt.Font("Raleway", 1, 36)); // NOI18N
        lbl_login_title.setText("Login");

        lbl_username_title.setFont(new java.awt.Font("Raleway", 1, 18)); // NOI18N
        lbl_username_title.setText("Usuario");

        lbl_pass_title.setFont(new java.awt.Font("Raleway", 1, 18)); // NOI18N
        lbl_pass_title.setText("Contraseña");

        lbl_olv_pass.setFont(new java.awt.Font("Raleway", 0, 10)); // NOI18N
        lbl_olv_pass.setText("Olvidé mi contraseña, haz click");

        lbl_click_aqui.setFont(new java.awt.Font("Raleway", 3, 10)); // NOI18N
        lbl_click_aqui.setForeground(new java.awt.Color(255, 153, 51));
        lbl_click_aqui.setText("AQUI");
        lbl_click_aqui.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_click_aquiMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(spt_login)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(lbl_olv_pass)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_click_aqui))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbl_pass_title)
                                .addComponent(lbl_username_title)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txt_login_pass)
                                    .addComponent(txt_login_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lbl_login_title)
                                .addGap(88, 88, 88))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(btn_ingresar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(lbl_login_title)
                .addGap(41, 41, 41)
                .addComponent(lbl_username_title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_login_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_pass_title)
                .addGap(18, 18, 18)
                .addComponent(txt_login_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_ingresar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(spt_login, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_olv_pass)
                    .addComponent(lbl_click_aqui))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

 
    private void btn_ingresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ingresarActionPerformed
        String correo = txt_login_usuario.getText(); // tu campo "Usuario" lo usas como correo
        String contraseña = new String(txt_login_pass.getPassword());

        if (correo.isEmpty()|| contraseña.isEmpty()) {
            logger.error("Usuario o contraseña no válidos.");
            return;
        }

        Usuario usuario = usuarioController.iniciarSesion(correo, contraseña);
        if (usuario != null) {
            if(usuario.getHabilitado().equals(false)){
                JOptionPane.showMessageDialog(
                    null,
                    "El usuario esta inhabilitado",
                    "Error",
                    JOptionPane.ERROR_MESSAGE
                );

                return;
            }
            SesionUsuario.getInstancia().iniciarSesion(
                    usuario.getIdUsuario(),
                    usuario.getNombre(),
                    usuario.getCorreo(),
                    usuario.getRol().getNombreRol()
            );

            AuditoriaLogger.registrar("LOGIN", "Inicio de sesión correctamente");
            setVisible(false);
            DashboardFrm dash = new DashboardFrm(LoginFrm.this);
            dash.configurarAccesosPorRol();
            txt_login_usuario.setText("");
            txt_login_pass.setText("");
            dash.setVisible(true);
        } else {
            logger.error("El usuario no fue encontrado en la base de datos o las credenciales del usuario están incorrectas.");
            JOptionPane.showMessageDialog(this, "Credenciales incorrectas", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_ingresarActionPerformed

    private void txt_login_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_login_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_login_usuarioActionPerformed

    private void lbl_click_aquiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_click_aquiMouseClicked
        CambiarPassFrm changeP = new CambiarPassFrm(LoginFrm.this);
        setVisible(false);
        changeP.setVisible(true);
    }//GEN-LAST:event_lbl_click_aquiMouseClicked

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ingresar;
    private javax.swing.JLabel lbl_click_aqui;
    private javax.swing.JLabel lbl_login_title;
    private javax.swing.JLabel lbl_olv_pass;
    private javax.swing.JLabel lbl_pass_title;
    private javax.swing.JLabel lbl_username_title;
    private javax.swing.JSeparator spt_login;
    private javax.swing.JPasswordField txt_login_pass;
    private javax.swing.JTextField txt_login_usuario;
    // End of variables declaration//GEN-END:variables
}
